import { Dimensions, StyleSheet } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAF9F5',
  },
  innerContainer: {
    flex: 1,
    backgroundColor: '#FAF9F5',
  },
  rowCentered: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  // Header
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0EDEC',
    backgroundColor: 'rgba(250, 249, 245, 0.9)',
  },
  headerLeft: { flex: 1, alignItems: 'flex-start' },
  headerRight: { flex: 1, alignItems: 'flex-end' },
  headerTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  pulseDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#8C8275',
    marginRight: 8,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2C2C2A',
  },
  iconBtn: {
    padding: 10,
    borderRadius: 20,
    backgroundColor: 'transparent',
  },
  // Sidebar (Drawer)
  sidebarOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.25)',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  sidebar: {
    width: width * 0.8,
    maxWidth: 320,
    height: '100%',
    backgroundColor: '#F5F3EC',
    borderLeftWidth: 1,
    borderLeftColor: '#E2DDD0',
    padding: 24,
  },
  sidebarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E2D9',
  },
  sidebarTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#2C2C2A',
  },
  sidebarDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#7D7568',
    marginLeft: 10,
  },
  sidebarActions: {
    marginTop: 16,
  },
  sidebarBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FAF9F5',
    borderWidth: 1,
    borderColor: '#DCD8CC',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  sidebarBtnText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#3D3A35',
  },
  historyContainer: {
    flex: 1,
    marginTop: 24,
  },
  historyTitle: {
    fontSize: 12,
    fontWeight: '500',
    color: '#7A756C',
  },
  historyCard: {
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'transparent',
    marginBottom: 10,
  },
  historyCardActive: {
    backgroundColor: '#FFF',
    borderColor: '#D0CBBE',
  },
  historyCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  historyDate: {
    fontSize: 11,
    color: '#8A857B',
  },
  historyPreview: {
    fontSize: 12,
    color: '#4A4741',
    lineHeight: 18,
    textAlign: 'right',
  },
  // Main Content Container
  mainContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  // Onboarding
  onboardingContainer: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 32,
  },
  onboardingHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  skipText: {
    fontSize: 12,
    color: '#8C8578',
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  dotsContainer: {
    flexDirection: 'row',
    gap: 6,
  },
  dot: {
    height: 6,
    width: 6,
    borderRadius: 3,
    backgroundColor: '#E2DDD0',
  },
  activeDot: {
    width: 28,
    backgroundColor: '#8C8275',
  },
  onboardingCenter: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 40,
  },
  onboardingIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#FAF8F2',
    borderWidth: 1,
    borderColor: '#E8E4D8',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
  },
  pulseInnerDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#8C8275',
  },
  onboardingTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: '#2C2C2A',
    textAlign: 'center',
  },
  onboardingFooter: {
    width: '100%',
    maxWidth: 320,
  },
  primaryBtnFull: {
    width: '100%',
    backgroundColor: '#3A3832',
    borderRadius: 16,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryBtnFullText: {
    color: '#F5F3EC',
    fontSize: 14,
    fontWeight: '500',
    marginHorizontal: 10,
  },
  // Login
  loginContainer: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 40,
  },
  loginCenter: {
    width: '100%',
    maxWidth: 320,
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  loginIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: '#FAF8F2',
    borderWidth: 1,
    borderColor: '#E2DDD0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  pulseInnerDotSmall: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#8C8275',
  },
  loginTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#2C2C2A',
    marginBottom: 4,
  },
  loginSubTitle: {
    fontSize: 12,
    color: '#8C8578',
    marginBottom: 32,
  },
  loginForm: {
    width: '100%',
    gap: 12,
  },
  input: {
    width: '100%',
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#DCD8CC',
    borderRadius: 16,
    padding: 16,
    fontSize: 12,
    marginBottom: 12,
    color: '#1A1A18',
  },
  secondaryBtnFull: {
    width: '100%',
    backgroundColor: '#EFECE6',
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
  },
  secondaryBtnFullText: {
    color: '#5A5A56',
    fontSize: 12,
    fontWeight: '500',
  },
  tertiaryBtnFull: {
    width: '100%',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: '#DCD8CC',
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
  },
  tertiaryBtnFullText: {
    color: '#3D3A35',
    fontSize: 12,
    fontWeight: '500',
  },
  footerText: {
    fontSize: 11,
    color: '#A29C91',
  },
  signupHeader: {
    width: '100%',
    maxWidth: 320,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  signupBackBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  signupBackText: {
    fontSize: 12,
    color: '#3D3A35',
    fontWeight: '500',
    marginRight: 4,
  },
  // Editor
  editorContainer: {
    flex: 1,
  },
  voiceBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFECE6',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  voiceBtnActive: {
    backgroundColor: '#E57373',
  },
  voiceBtnText: {
    fontSize: 12,
    color: '#5A5A56',
    marginRight: 6,
  },
  editorInput: {
    flex: 1,
    minHeight: 320,
    fontSize: 18,
    color: '#1A1A18',
    lineHeight: 28,
  },
  editorFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#F0EDEC',
  },
  charCountText: {
    fontSize: 11,
    color: '#A29C91',
  },
  listeningText: {
    fontSize: 12,
    color: '#8A857B',
    marginRight: 6,
  },
  listeningDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#8C8275',
  },
  fabContainer: {
    position: 'absolute',
    bottom: 29,
    width: '100%',
    alignItems: 'center',
    transform: [{ translateX: 4 }],
  },
  fabBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#3A3832',
    paddingVertical: 16,
    paddingHorizontal: 28,
    borderRadius: 30,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  fabText: {
    color: '#F5F3EC',
    fontSize: 14,
    fontWeight: '500',
  },
  fabCircleBtn: {
    position: 'absolute',
    bottom: 39,
    left: -6,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#3A3832',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  // Result View
  resultContainer: {
    paddingBottom: 80,
  },
  resultSnippet: {
    backgroundColor: '#F2EFE7',
    borderWidth: 1,
    borderColor: '#E5E1D5',
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
  },
  snippetLabel: {
    fontSize: 10,
    fontWeight: '500',
    color: '#8C8578',
    marginBottom: 6,
    textAlign: 'right',
  },
  snippetText: {
    fontSize: 12,
    color: '#1A1A18',
    lineHeight: 20,
    textAlign: 'right',
  },
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B6152',
  },
  empathyBox: {
    backgroundColor: '#F5F2E9',
    borderWidth: 1,
    borderColor: '#E8E4D8',
    borderRadius: 16,
    padding: 16,
  },
  empathyText: {
    fontSize: 16,
    color: '#2C2C2A',
    lineHeight: 26,
    textAlign: 'right',
  },
  ideaCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-end',
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#EAE6DC',
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
  },
  ideaText: {
    flex: 1,
    fontSize: 14,
    color: '#3D3A35',
    lineHeight: 22,
    textAlign: 'right',
    marginRight: 12,
  },
  ideaNumberBox: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#EFECE3',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  ideaNumber: {
    fontSize: 12,
    fontWeight: '500',
    color: '#787164',
  },
  hintText: {
    fontSize: 11,
    color: '#8C8578',
  },
  stepCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-end',
    backgroundColor: '#FAF8F2',
    borderWidth: 1,
    borderColor: '#E5E0D3',
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
  },
  stepCardDone: {
    backgroundColor: '#EDF4F0',
    borderColor: '#D1E3D8',
  },
  stepText: {
    flex: 1,
    fontSize: 14,
    color: '#3D3A35',
    lineHeight: 22,
    textAlign: 'right',
    marginRight: 12,
  },
  stepTextDone: {
    color: '#557A69',
    textDecorationLine: 'line-through',
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#B2ACA0',
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  checkboxDone: {
    backgroundColor: '#557A69',
    borderColor: '#557A69',
  },
  reflectiveBox: {
    backgroundColor: '#EEFAF4',
    borderWidth: 1,
    borderColor: '#D2EFE0',
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
  },
  reflectiveText: {
    fontSize: 14,
    color: '#1B4332',
    lineHeight: 24,
    textAlign: 'right',
  },
  resultActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#EFECE6',
    paddingTop: 16,
  },
  actionBtn: {
    padding: 10,
    backgroundColor: '#EFECE6',
    borderRadius: 10,
  },
  rowCenteredAction: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFECE6',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  newSessionText: {
    fontSize: 12,
    color: '#8A857B',
  },
  // Settings
  settingsContainer: {
    paddingBottom: 40,
  },
  settingsLabel: {
    fontSize: 12,
    color: '#8C8578',
    textAlign: 'right',
    marginBottom: 12,
  },
  settingsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#EAE6DC',
    borderRadius: 16,
    padding: 16,
    marginBottom: 8,
  },
  settingsIconBox: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#F4F1EA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsCardTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: '#2C2C2A',
    marginBottom: 2,
  },
  settingsCardSub: {
    fontSize: 11,
    color: '#8A857B',
  },
  // Modals
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContent: {
    width: '100%',
    maxWidth: 320,
    backgroundColor: '#FAF9F5',
    borderWidth: 1,
    borderColor: '#E2DDD0',
    borderRadius: 24,
    padding: 32,
    alignItems: 'center',
  },
  modalCloseBtn: {
    position: 'absolute',
    top: 16,
    right: 16,
    padding: 8,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '500',
    color: '#2C2C2A',
    marginBottom: 6,
  },
  modalSubTitle: {
    fontSize: 12,
    color: '#7A756C',
    marginBottom: 24,
  },
  breathCircle: {
    width: 128,
    height: 128,
    borderRadius: 64,
    borderWidth: 4,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 32,
  },
  breathIn: { borderColor: '#557A69', backgroundColor: '#EEF5F1', transform: [{ scale: 1.1 }] },
  breathHold: { borderColor: '#D29B52', backgroundColor: '#FAF4EB', transform: [{ scale: 1.05 }] },
  breathOut: { borderColor: '#6B82A8', backgroundColor: '#EEF2F8', transform: [{ scale: 0.9 }] },
  breathPhaseText: {
    fontSize: 18,
    fontWeight: '500',
    color: '#2C2C2A',
  },
  breathTimerText: {
    fontSize: 24,
    fontWeight: '600',
    color: '#3D3A35',
    marginTop: 4,
  },
  primaryBtn: {
    width: '100%',
    backgroundColor: '#3A3832',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  primaryBtnText: {
    color: '#F5F3EC',
    fontSize: 12,
    fontWeight: '500',
  },
  secondaryBtn: {
    width: '100%',
    backgroundColor: '#EFECE6',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  secondaryBtnText: {
    color: '#5A5A56',
    fontSize: 12,
    fontWeight: '500',
  },
  logoutIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FAF0F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
});